# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'SC-Subscription1'
    subscriptionId: 'd6ba570b-67e9-42bc-bafd-d85070e4a5e5'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmParametersFile: '/main.bicep'
    deploymentMode: 'Incremental'